// Generated by CoffeeScript 2.2.2
var load_data;

import csv from 'csvdata';

load_data = async function() {
  var data;
  data = (await csvdata.load('./my-file.csv'));
  return console.log(data);
};

load_data();
